# Generated by Django 5.1.4 on 2024-12-13 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quizapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Useranswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField()),
                ("score", models.IntegerField(default=0)),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Quizapp.questionbank",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
